feat: flutter layout integrated with yoga
ZupIT/yoga pull request #14
Opened 2021-06-11 02:21 UTC by matheusribeirozup

Signed-off-by: Matheus Ribeiro <matheus.ribeiro@zup.com.br>

This PR adds two layout components:
`YogaTree`:  receive a node and a list of child widgets.
`YogaLeaf`: receive a node, a boolean to tell if is the last component in the tree and a child.

These components are the bridge between yoga and flutter.

2021-06-23 12:43 UTC, dantes-git approved these changes

2021-06-23 12:43 UTC, dantes-git commented on flutter/example/lib/main.dart
> +              YogaLeaf(
I am confused by YogaLeaf because they can receive YogaTree as it seems, in which case it would no longer be a leaf in the hierarchy.

2021-06-23 16:54 UTC, matheusribeirozup commented on flutter/example/lib/main.dart
> +              YogaLeaf(
As discussed, we changed the names to better readability:
`YogaTree` -> `YogaLayout`
`YogaLeaf` -> `YogaNode`
`YogaNode` -> `NodeProperties`

2021-06-23 18:47 UTC, dantes-git requested changes

2021-06-23 18:47 UTC, dantes-git commented on flutter/README.md
> +All that done, just configure each `YogaProperties` instance to all `YogaLayout` and `YogaNode`
```suggestion
All that done, just configure each `NodeProperties` instance to all `YogaLayout` and `YogaNode` 
```

2021-06-23 18:47 UTC, dantes-git commented on flutter/README.md
> +YogaNode child = NodeProperties();
```suggestion
NodeProperties child = NodeProperties();
```

2021-06-23 18:47 UTC, dantes-git commented on flutter/example/example.md
> +    child1.setHeight(50);
We need to update this file to the new names

2021-06-23 21:13 UTC, dantes-git submitted a review, later dismissed

2021-06-24 12:23 UTC, dantes-git approved these changes

2021-06-24 14:12 UTC, uziasferreirazup approved these changes

2021-06-24 14:27 UTC, merged